language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
install:
  - "pip install flake8 --use-mirrors"

before_script: "flake8 qhost/*.py bin/qhost --ignore=F401"

script: "python ./test/run.py"
